### ISSUE TITLE
vue version

### ISSUE THREAD

**Issue by joshua1** [SmallComfort/react-vue#7]
Hi @SmallComfort any plans to upgrade the version of vue in use here

**Comment by joshua1** [comment]
@SmallComfort  any feedback here ?

**Comment by SmallComfort** [comment]
Hello, A long waiting reply.

React-Vue only use the reactivity system of Vue, and the reactivity system is quite stable. At least in the Vue's version of 2.x, you can use it with confidence. 

The problem occurred in the React version. Since React released a new version (16.x)，its rendering has changed a lot. I can't guarantee normal use in this new verion.
